// Generated by CoffeeScript 1.10.0
(function() {
  var goToSection, nextSection;

  $('#ad').validate({
    success: function(label) {
      return label.addClass('valid').text('?');
    },
    error: function() {},
    onsubmit: false,
    rules: {
      phone: {
        required: true,
        phonePL: true
      }
    }
  });

  $('body').on('keyup', 'form', function(e) {
    if (e.which === 13) {
      if ($('#next').is(':visible') && $('fieldset.current').find('input, textarea').valid()) {
        e.preventDefault();
        nextSection();
        return false;
      }
    }
  });

  $('#next').on('click', function(e) {
    return nextSection();
  });

  $('form').on('submit', function(e) {
    if ($('#next').is(':visible') || $('fieldset.current').index() < 4) {
      return e.preventDefault();
    }
  });

  goToSection = function(i) {
    $('fieldset:gt(' + i + ')').removeClass('current').addClass('next');
    $('fieldset:lt(' + i + ')').removeClass('current');
    $('li').eq(i).addClass('current').siblings().removeClass('current');
    return setTimeout((function() {
      $('fieldset').eq(i).removeClass('next').addClass('current active');
      if ($('fieldset.current').index() === 4) {
        $('#next').hide();
        return $('input[type=submit]').show();
      } else {
        $('#next').show();
        return $('input[type=submit]').hide();
      }
    }), 80);
  };

  nextSection = function() {
    var i;
    i = $('fieldset.current').index();
    if (i < 4 && $('fieldset.current').find('input, textarea').valid()) {
      $('li').eq(i + 1).addClass('active');
      return goToSection(i + 1);
    }
  };

  $('li').on('click', function(e) {
    var i;
    i = $(this).index();
    if ($(this).hasClass('active')) {
      return goToSection(i);
    }
  });

  jQuery.validator.addMethod('phonePL', (function(phone_number, element) {
    phone_number = phone_number.replace(/\s+/g, '');
    return this.optional(element) || phone_number.length > 9 && phone_number.match(/^([0-9]{9})|(([0-9]{3}-){2}[0-9]{3})|(\d\d\d \d\d\d \d\d\d)|(\(\d\d\)\d\d\d\d\d\d\d)$/);
  }), 'Prosz� o podanie prawid�owego numeru telefonu');

}).call(this);

//# sourceMappingURL=form.js.map
